#!/bin/bash

if (grep -q "dns=none" /etc/NetworkManager/NetworkManager.conf 2>/dev/null); then
echo -e "\e[1;32;40m Required entry already in place \e[0m"
exit 0
else
echo -e "\e[1;33;40m updating entry on NetworkManager.conf \e[0m"
sed -i '/\[main/a dns=none' /etc/NetworkManager/NetworkManager.conf
fi
echo -e "\e[1;33;40m Restart NetworkManager \e[0m"
systemctl restart NetworkManager.service
